## 26th Feb Assignment
### Numpy Basic

---

```
Consider the below code to answer further questions:
```
```python
import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)
```

---

```
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans. Yes, there is a difference in the data types of the variables list_ and array_list. The list_ variable is a Python list containing strings, while the array_list variable is a NumPy array.

To print the data types of both variables, you can use the type() function.
```

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


---

```
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

Ans. To print the data type of each element in both the list_ and array_list variables, you can use a loop to iterate through the elements and apply the type() function to each element. 
```

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
for element in list_:
    print(type(element))

# Print data types of elements in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


---

```
Q3. Considering the following changes in the variable, array_list:
```
```python
array_list = np.array(object = list_, dtype = int)
```
```
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans. Yes, there will be a difference in the data types of the elements present in list_ and array_list after the modification. By specifying dtype=int when creating the NumPy array, the elements in array_list will be converted to integers. Here's the code to print the data types of each element in both variables:
```

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
for element in list_:
    print(type(element))

# Print data types of elements in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


---

```
Consider the below code to answer further questions:
```
```python
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
```

In [4]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

```
Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

Ans.
```

In [5]:
# (i) Shape
shape = num_array.shape
print("Shape:", shape)

# (ii) Size
size = num_array.size
print("Size:", size)

Shape: (2, 3)
Size: 6


---

```
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

Ans.
```

In [6]:
arr = np.zeros((3,3))
print(arr)

# (i) Shape
shape1 = arr.shape
print("Shape:", shape1)

# (ii) Size
size1 = arr.size
print("Size:", size1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (3, 3)
Size: 9


---

```
Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Ans.
```

In [7]:
ident = np.eye(5)
print(ident)

# (i) Shape
shape1 = ident.shape
print("Shape:", shape1)

# (ii) Size
size1 = ident.size
print("Size:", size1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape: (5, 5)
Size: 25


---